[tool.poetry]
name = "exogen-discord-bot"
version = "0.1.0"
description = "Python bot for integrating Exogen with it's Discord server."
authors = ["Drew Tschetter <@dchedz>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.9"
asyncio = "^3.4.3"
discord = "^1.0.1"
Flask = "^1.1.2"
numpy = "^1.19.5"
DateTime = "^4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
